#!/bin/bash

echo "=== FeedMob AdPilot MCP Setup Verification ==="
echo ""

echo "✓ Checking project structure..."
[ -f "package.json" ] && echo "  ✓ package.json exists"
[ -f "tsconfig.json" ] && echo "  ✓ tsconfig.json exists"
[ -f "vitest.config.ts" ] && echo "  ✓ vitest.config.ts exists"
[ -f ".env.example" ] && echo "  ✓ .env.example exists"
[ -f "README.md" ] && echo "  ✓ README.md exists"

echo ""
echo "✓ Checking source directories..."
[ -d "src/config" ] && echo "  ✓ src/config/"
[ -d "src/services" ] && echo "  ✓ src/services/"
[ -d "src/tools" ] && echo "  ✓ src/tools/"
[ -d "src/types" ] && echo "  ✓ src/types/"
[ -d "src/utils" ] && echo "  ✓ src/utils/"
[ -d "src/db" ] && echo "  ✓ src/db/"

echo ""
echo "✓ Checking test directories..."
[ -d "tests/unit" ] && echo "  ✓ tests/unit/"
[ -d "tests/integration" ] && echo "  ✓ tests/integration/"
[ -d "tests/property" ] && echo "  ✓ tests/property/"
[ -d "tests/arbitraries" ] && echo "  ✓ tests/arbitraries/"

echo ""
echo "✓ Checking key source files..."
[ -f "src/index.ts" ] && echo "  ✓ src/index.ts"
[ -f "src/config/environment.ts" ] && echo "  ✓ src/config/environment.ts"
[ -f "src/config/database.ts" ] && echo "  ✓ src/config/database.ts"
[ -f "src/services/auth.service.ts" ] && echo "  ✓ src/services/auth.service.ts"
[ -f "src/services/claude.service.ts" ] && echo "  ✓ src/services/claude.service.ts"
[ -f "src/services/database.service.ts" ] && echo "  ✓ src/services/database.service.ts"
[ -f "src/services/image.service.ts" ] && echo "  ✓ src/services/image.service.ts"
[ -f "src/services/ui.service.ts" ] && echo "  ✓ src/services/ui.service.ts"

echo ""
echo "✓ Checking database migrations..."
[ -f "src/db/migrations/001_create_users.sql" ] && echo "  ✓ 001_create_users.sql"
[ -f "src/db/migrations/002_create_campaigns.sql" ] && echo "  ✓ 002_create_campaigns.sql"
[ -f "src/db/migrations/003_create_creative_assets.sql" ] && echo "  ✓ 003_create_creative_assets.sql"
[ -f "src/db/schema.sql" ] && echo "  ✓ schema.sql"
[ -f "src/db/migrate.ts" ] && echo "  ✓ migrate.ts"
[ -f "src/db/reset.ts" ] && echo "  ✓ reset.ts"

echo ""
echo "✓ Checking tool definitions..."
[ -f "src/tools/parseCampaignRequest.ts" ] && echo "  ✓ parseCampaignRequest.ts"
[ -f "src/tools/generateAdCopy.ts" ] && echo "  ✓ generateAdCopy.ts"
[ -f "src/tools/generateAdImages.ts" ] && echo "  ✓ generateAdImages.ts"
[ -f "src/tools/generateMixedMedia.ts" ] && echo "  ✓ generateMixedMedia.ts"
[ -f "src/tools/getCampaignHistory.ts" ] && echo "  ✓ getCampaignHistory.ts"

echo ""
echo "=== Setup Verification Complete ==="
echo ""
echo "Next steps:"
echo "1. Run 'npm install' to install dependencies"
echo "2. Copy .env.example to .env and configure"
echo "3. Set up PostgreSQL database"
echo "4. Run 'npm run db:migrate' to create tables"
echo "5. Run 'npm run dev' to start the server"
